spring:
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 10001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/rpm-eureka/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: http://localhost:8762/rpm-auth/
    statusPageUrl: http://localhost:8762/rpm-auth/actuator/info
    healthCheckUrl: http://localhost:8762/rpm-auth/actuator/health
    homePageUrl: http://localhost:8762/rpm-auth/
    instance-id: auth-service
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  jwt:
    secret: ${RPM_JWT_SECRET}
