server:
  port: 8762
  tomcat:
    max-http-post-size: 2MB
    max-swallow-size: 2MB
  
spring:  
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true

ribbon:
  ReadTimeout: 9999999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/rpm-eureka/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: http://localhost:8762/rpm-zuul
    statusPageUrl: http://localhost:8762/rpm-zuul/actuator/info
    healthCheckUrl: http://localhost:8762/rpm-zuul/actuator/health
    homePageUrl: http://localhost:8762/rpm-zuul
    instance-id: zuul-service

zuul:
  ignored-services: '*'
  routes:
    auth-service:
      path: /auth/**
      url: http://localhost:8762/rpm-auth
      service-id: auth-service
      strip-prefix: true
      sensitive-headers: Cookie,Set-Cookie
    project-service:
      path: /projects/**
      url: http://localhost:8762/rpm-project
      service-id: project-service
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
security:
  jwt:
    secret: ${RPM_JWT_SECRET}
